### GET ENV VARIABLES

GET http://localhost:3000/auth/env


### Signup User

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Houti",
    "lastName": "Yaman",
    "email": "yaminahouti@taptoplab.com",
    "password": "123456"
}

### Login User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "yaminahouti@taptoplab.com",
    "password": "123456"
}

### Send Email

POST http://localhost:3000/email/send-email
Content-Type: application/json

{
  "recipients": ["taiwooa.19@student.funaab.edu.ng"],
  "subject": "Test Email",
  "html": "This is a test email sent from the Nestjs application. <br> It is sent using the <a href=\"https://nodemailer.com/about/\">Nodemailer</a> package.",
  "text": "This is a test email sent from the Nestjs application. It is sent using the Nodemailer package."
}


### Verify Token

POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
 "token": "879af8164e13ff9c8ece63bb900e1c64ef7c10bf83799d72b6db6bb3b76aeb53"
}

### Verify OTP

POST http://localhost:3000/auth/verify-otp
Content-Type: application/json

{
 "tempToken": "90c251c6-e745-4422-830a-4b43cfcc720b",
 "otp": "801913"
}

