### GET ENV VARIABLES

GET http://localhost:3000/auth/env


### Signup User

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Avlon",
    "lastName": "Hinbox",
    "email": "avlon@24hinbox.com",
    "password": "123456"
}

### Login User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "avlon@24hinbox.com",
    "password": "123456"
}

### Send Email

POST http://localhost:3000/email/send-email
Content-Type: application/json

{
  "recipients": ["taiwooa.19@student.funaab.edu.ng"],
  "subject": "Test Email",
  "html": "This is a test email sent from the Nestjs application. <br> It is sent using the <a href=\"https://nodemailer.com/about/\">Nodemailer</a> package.",
  "text": "This is a test email sent from the Nestjs application. It is sent using the Nodemailer package."
}


### Verify Token

POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
 "token": "472973d3f01497afa48549538d39f9fe2cf5eb5bfd09edc22bfe53d9d1bfa12e"
}

